### ISSUE TITLE
Could please share the ROP image dataset, to run the scripts

### ISSUE THREAD

**Issue by Akhileshkakade** [aygo29/retinopathy_of_prematurity_detection#1]

**Comment by aygo29** [comment]
Unfortunately, I cannot share the data publicly as it is property of Narayana Nethralaya Hospitals. 
You can try it on public datasets like this - https://data.mendeley.com/datasets/xw5xc7xrmp/2, https://www.kaggle.com/c/aptos2019-blindness-detection/data

**Comment by Akhileshkakade** [comment]
Hi,

Thanks for sharing public ROP datasets.
Could please share the contact of Narayan Nethralaya Hospital, Bangalore
where I can request for ROP dataset.

I am working on ROP research topic for my Ph.D. That would be really
helpful.

Regards,
Akhilesh

**Comment by aygo29** [comment]
That's great to hear! 
The data was provided by Dr. Anand Vinekar, who has done a lot of ROP related research.
You can try contacting him for the data - anandvinekar@yahoo.com

**Comment by Akhileshkakade** [comment]
Thanks I will contact it.
